name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? Include steps to reproduce if possible.
      placeholder: |
        What happened:
        ...

        Steps to reproduce:
        1. Run `ralph ...`
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any error messages or output
      render: shell

  - type: input
    id: version
    attributes:
      label: ralph-starter Version
      description: Run `ralph --version` to get this
      placeholder: "0.2.1"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: OS, Node.js version, or any other relevant info
