name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like ralph to do? What problem does it solve?
      placeholder: |
        I would like ralph to...

        Problem it solves:
        ...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Examples, mockups, alternatives considered, or any other relevant info
