name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: I would like ralph to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - New Integration (Linear, Notion, GitHub, etc.)
        - CLI Experience
        - AI/LLM Enhancement
        - Configuration
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How significant is this change?
      options:
        - Small (minor tweak)
        - Medium (new command or option)
        - Large (major feature or new integration)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
